- name: Install initial packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg

#- name: Install docker repo key to apt
#  become: true
#  ansible.builtin.apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install docker repo key to apt
  become: true
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

- shell: lsb_release -sc
  register: os_codename

- name: Install docker repository to apt
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu "{{ os_codename.stdout }}" stable
    state: present

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  register: install_docker_result

- name: Reboot the machine to make the docker.service start # see: https://bbs.archlinux.org/viewtopic.php?id=267694
  become: true
  reboot:
  when: install_docker_result.changed is true

- name: Enable docker.service
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Create "docker" group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to "docker" group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Add usefull alias for docker
  ansible.builtin.blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    block: |
      alias d="docker"
      alias docker-compose="docker compose"
      alias dc="docker compose"
      complete -F _docker docker-compose dc
      complete -F _docker docker d
    marker: '# {mark} ANSIBLE MANAGED BLOCK - usefull bash aliases'
    append_newline: true
    prepend_newline: true
    create: yes
