
- name: Setup sshd
  block:
  - name: Update sshd_config
    become: true
    blockinfile:
      dest: "/etc/ssh/sshd_config"
      insertafter: "^Include /etc/ssh/sshd_config"
      block: |
        {{ ssh_setup.sshd_config }}
  - name: Restart sshd service
    become: true
    service:
      name: sshd
      state: restarted
      enabled: true
