
- name: Setup sshd
  block:
  - name: Update sshd_config
    become: true
    ansible.builtin.blockinfile:
      dest: "/etc/ssh/sshd_config"
      insertafter: "^Include /etc/ssh/sshd_config"
      block: |
        {{ ssh_setup.sshd_config }}

- name: enable ssh service on systemboot
  block:
    - name: enable sshd service
      become: true
      ansible.builtin.service:
        name: sshd
        enabled: true
    - name: enable ssh service
      become: true
      ansible.builtin.service:
        name: ssh
        enabled: true
  ignore_errors: true

- name: Restart ssh
  block:
    - name: restart sshd service
      become: true
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: restart ssh service
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted
  ignore_errors: true
